export const bands = [
  {
    north: [
      {
        name: "Don Broco",
        stage: "Rock Scene Stage",
        start: "20:50",
        end: "22:00",
      },
      {
        name: "Waterparks",
        stage: "Rock Scene Stage",
        start: "19:35",
        end: "20:20",
      },
      {
        name: "State Champs",
        stage: "Rock Scene Stage",
        start: "18:25",
        end: "19:10",
      },
      {
        name: "Mayday Parade",
        stage: "Rock Scene Stage",
        start: "17:15",
        end: "18:00",
      },
      {
        name: "We Are The In Crowd",
        stage: "Rock Scene Stage",
        start: "16:10",
        end: "16:50",
      },
      {
        name: "Creeper",
        stage: "Rock Scene Stage",
        start: "15:05",
        end: "15:45",
      },
      {
        name: "As It Is",
        stage: "Rock Scene Stage",
        start: "14:05",
        end: "14:40",
      },
      {
        name: "HelloGoodbye",
        stage: "Rock Scene Stage",
        start: "13:10",
        end: "13:45",
      },
      {
        name: "ROAM",
        stage: "Rock Scene Stage",
        start: "12:20",
        end: "12:50",
      },
      {
        name: "The Bottom Line",
        stage: "Rock Scene Stage",
        start: "11:30",
        end: "12:00",
      },
      {
        name: "NOFX",
        stage: "punk in drublic",
        start: "20:55",
        end: "22:00",
      },
      {
        name: "Alkaline Trio",
        stage: "punk in drublic",
        start: "19:35",
        end: "20:25",
      },
      {
        name: "Anti-Flag",
        stage: "punk in drublic",
        start: "18:35",
        end: "19:15",
      },
      {
        name: "The Skints",
        stage: "punk in drublic",
        start: "17:35",
        end: "18:15",
      },
      {
        name: "Zebrahead",
        stage: "punk in drublic",
        start: "16:35",
        end: "17:15",
      },
      {
        name: "Frank Turner & The Sleeping Souls",
        stage: "punk in drublic",
        start: "15:25",
        end: "16:15",
      },
      {
        name: "Capdown",
        stage: "punk in drublic",
        start: "14:25",
        end: "15:05",
      },
      {
        name: "Snuff",
        stage: "punk in drublic",
        start: "13:25",
        end: "14:05",
      },
      {
        name: "The Baboon Show",
        stage: "punk in drublic",
        start: "12:35",
        end: "13:05",
      },
      {
        name: "Buster Shuffle",
        stage: "punk in drublic",
        start: "11:45",
        end: "12:15",
      },

      {
        name: "While She Sleeps",
        stage: "Jägermeister Tent",
        start: "20:00",
        end: "21:00",
      },
      {
        name: "Bury Tomorrow",
        stage: "Jägermeister Tent",
        start: "18:55",
        end: "19:55",
      },
      {
        name: "Skindred",
        stage: "Jägermeister Tent",
        start: "18:00",
        end: "18:50",
      },
      {
        name: "Funeral for a Friend",
        stage: "Jägermeister Tent",
        start: "17:05",
        end: "17:55",
      },
      {
        name: "Trash Boat",
        stage: "Jägermeister Tent",
        start: "16:20",
        end: "17:00",
      },
      {
        name: "Your Demise",
        stage: "Jägermeister Tent",
        start: "15:40",
        end: "16:20",
      },
      {
        name: "Comeback Kid",
        stage: "Jägermeister Tent",
        start: "15:00",
        end: "15:40",
      },
      {
        name: "Maleviolence",
        stage: "Jägermeister Tent",
        start: "14:25",
        end: "15:00",
      },
      {
        name: "Deez Nuts",
        stage: "Jägermeister Tent",
        start: "13:45",
        end: "14:20",
      },
      {
        name: "Brutality Will Prevail",
        stage: "Jägermeister Tent",
        start: "13:10",
        end: "13:45",
      },
      {
        name: "Loathe",
        stage: "Jägermeister Tent",
        start: "12:40",
        end: "13:10",
      },
      {
        name: "Hacktivist",
        stage: "Jägermeister Tent",
        start: "12:10",
        end: "12:40",
      },
      {
        name: "Blood Youth",
        stage: "Jägermeister Tent",
        start: "11:40",
        end: "12:10",
      },
      {
        name: "Boston Manor",
        stage: "The Key Club Stage (Left Key)",
        start: "20:20",
        end: "20:55",
      },

      {
        name: "Holding Absense",
        stage: "The Key Club Stage (Right Key)",
        start: "19:40",
        end: "20:15",
      },
      {
        name: "Normandie",
        stage: "The Key Club Stage (Left Key)",
        start: "19:05",
        end: "19:35",
      },
      {
        name: "[Spunge]",
        stage: "The Key Club Stage (Right Key)",
        start: "18:30",
        end: "19:00",
      },
      {
        name: "Vukovi",
        stage: "The Key Club Stage (Left Key)",
        start: "17:55",
        end: "18:25",
      },
      {
        name: "Lizzy Farrall",
        stage: "The Key Club Stage (Right Key)",
        start: "17:20",
        end: "17:50",
      },
      {
        name: "Wargasm",
        stage: "The Key Club Stage (Left Key)",
        start: "16:45",
        end: "17:15",
      },
      {
        name: "Static Dress",
        stage: "The Key Club Stage (Right Key)",
        start: "16:10",
        end: "16:40",
      },
      {
        name: "Popes of Chillitown",
        stage: "The Key Club Stage (Left Key)",
        start: "15:35",
        end: "16:05",
      },
      {
        name: "Noahfinnce",
        stage: "The Key Club Stage (Right Key)",
        start: "15:00",
        end: "15:30",
      },
      {
        name: "A",
        stage: "The Key Club Stage (Left Key)",
        start: "14:25",
        end: "14:55",
      },
      {
        name: "Secret Special Guests",
        stage: "The Key Club Stage (Right Key)",
        start: "13:50",
        end: "14:20",
      },
      {
        name: "Weatherstate",
        stage: "The Key Club Stage (Left Key)",
        start: "13:15",
        end: "13:45",
      },
      {
        name: "Doll Skin",
        stage: "The Key Club Stage (Right Key)",
        start: "12:40",
        end: "13:10",
      },
      {
        name: "The Hara",
        stage: "The Key Club Stage (Right Key)",
        start: "12:05",
        end: "12:35",
      },
      {
        name: "For You The Moon",
        stage: "The Key Club Stage (Right Key)",
        start: "11:30",
        end: "12:00",
      },
      {
        name: "Zoe London DJ Set",
        stage: "Jägermeister Tent",
        start: "22:00",
        end: "22:55",
      },
    ],
  },
  {
    south: [
      {
        name: "Don Broco",
        stage: "Rock Scene Stage",
        start: "20:50",
        end: "22:00",
      },
      {
        name: "Waterparks",
        stage: "Rock Scene Stage",
        start: "19:35",
        end: "20:20",
      },
      {
        name: "State Champs",
        stage: "Rock Scene Stage",
        start: "18:25",
        end: "19:10",
      },
      {
        name: "Mayday Parade",
        stage: "Rock Scene Stage",
        start: "17:15",
        end: "18:00",
      },
      {
        name: "We Are The In Crowd",
        stage: "Rock Scene Stage",
        start: "16:10",
        end: "16:50",
      },
      {
        name: "Creeper",
        stage: "Rock Scene Stage",
        start: "15:05",
        end: "15:45",
      },
      {
        name: "As It Is",
        stage: "Rock Scene Stage",
        start: "14:05",
        end: "14:40",
      },
      {
        name: "HelloGoodbye",
        stage: "Rock Scene Stage",
        start: "13:10",
        end: "13:45",
      },
      {
        name: "ROAM",
        stage: "Rock Scene Stage",
        start: "12:20",
        end: "12:50",
      },
      {
        name: "The Bottom Line",
        stage: "Rock Scene Stage",
        start: "11:30",
        end: "12:00",
      },
      {
        name: "NOFX",
        stage: "punk in drublic",
        start: "20:55",
        end: "22:00",
      },
      {
        name: "Frank Turner & The Sleeping Souls",
        stage: "punk in drublic",
        start: "19:35",
        end: "20:25",
      },
      {
        name: "Alkaline Trio",
        stage: "punk in drublic",
        start: "18:25",
        end: "19:15",
      },
      {
        name: "Anti-Flag",
        stage: "punk in drublic",
        start: "17:25",
        end: "18:05",
      },
      {
        name: "The Skints",
        stage: "punk in drublic",
        start: "16:25",
        end: "17:05",
      },
      {
        name: "Zebrahead",
        stage: "punk in drublic",
        start: "15:25",
        end: "16:05",
      },

      {
        name: "Capdown",
        stage: "punk in drublic",
        start: "14:25",
        end: "15:05",
      },
      {
        name: "Snuff",
        stage: "punk in drublic",
        start: "13:25",
        end: "14:05",
      },

      {
        name: "Buster Shuffle",
        stage: "punk in drublic",
        start: "12:35",
        end: "13:05",
      },
      {
        name: "The Baboon Show",
        stage: "punk in drublic",
        start: "11:45",
        end: "12:15",
      },

      {
        name: "While She Sleeps",
        stage: "Jägermeister Tent",
        start: "20:00",
        end: "21:00",
      },
      {
        name: "Bury Tomorrow",
        stage: "Jägermeister Tent",
        start: "18:55",
        end: "19:55",
      },
      {
        name: "Skindred",
        stage: "Jägermeister Tent",
        start: "18:00",
        end: "18:50",
      },
      {
        name: "Funeral for a Friend",
        stage: "Jägermeister Tent",
        start: "17:05",
        end: "17:55",
      },
      {
        name: "Trash Boat",
        stage: "Jägermeister Tent",
        start: "16:20",
        end: "17:00",
      },
      {
        name: "Your Demise",
        stage: "Jägermeister Tent",
        start: "15:40",
        end: "16:20",
      },
      {
        name: "Comeback Kid",
        stage: "Jägermeister Tent",
        start: "15:00",
        end: "15:40",
      },
      {
        name: "Maleviolence",
        stage: "Jägermeister Tent",
        start: "14:25",
        end: "15:00",
      },
      {
        name: "Deez Nuts",
        stage: "Jägermeister Tent",
        start: "13:45",
        end: "14:20",
      },
      {
        name: "Brutality Will Prevail",
        stage: "Jägermeister Tent",
        start: "13:10",
        end: "13:45",
      },
      {
        name: "Loathe",
        stage: "Jägermeister Tent",
        start: "12:40",
        end: "13:10",
      },
      {
        name: "Hacktivist",
        stage: "Jägermeister Tent",
        start: "12:10",
        end: "12:40",
      },
      {
        name: "Blood Youth",
        stage: "Jägermeister Tent",
        start: "11:40",
        end: "12:10",
      },
      {
        name: "Boston Manor",
        stage: "The Key Club Stage (Left Key)",
        start: "20:20",
        end: "20:55",
      },

      {
        name: "Holding Absense",
        stage: "The Key Club Stage (Right Key)",
        start: "19:40",
        end: "20:15",
      },
      {
        name: "Vukovi",
        stage: "The Key Club Stage (Left Key)",
        start: "19:05",
        end: "19:35",
      },
      {
        name: "Static Dress",
        stage: "The Key Club Stage (Right Key)",
        start: "18:30",
        end: "19:00",
      },
      {
        name: "Normandie",
        stage: "The Key Club Stage (Left Key)",
        start: "17:55",
        end: "18:25",
      },
      {
        name: "[Spunge]",
        stage: "The Key Club Stage (Right Key)",
        start: "17:20",
        end: "17:50",
      },
      {
        name: "A",
        stage: "The Key Club Stage (Left Key)",
        start: "16:45",
        end: "17:15",
      },
      {
        name: "Secret Special Guests",
        stage: "The Key Club Stage (Right Key)",
        start: "16:10",
        end: "16:40",
      },
      {
        name: "Wargasm",
        stage: "The Key Club Stage (Left Key)",
        start: "15:35",
        end: "16:05",
      },
      {
        name: "Lizzy Farrall",
        stage: "The Key Club Stage (Right Key)",
        start: "15:00",
        end: "15:30",
      },
      {
        name: "Weatherstate",
        stage: "The Key Club Stage (Left Key)",
        start: "14:25",
        end: "14:55",
      },
      {
        name: "Doll Skin",
        stage: "The Key Club Stage (Right Key)",
        start: "13:50",
        end: "14:20",
      },
      {
        name: "The Hara",
        stage: "The Key Club Stage (Left Key)",
        start: "13:15",
        end: "13:45",
      },
      {
        name: "Noahfinnce",
        stage: "The Key Club Stage (Right Key)",
        start: "12:40",
        end: "13:10",
      },

      {
        name: "Popes of Chillitown",
        stage: "The Key Club Stage (Left Key)",
        start: "12:05",
        end: "12:35",
      },
      {
        name: "For You The Moon",
        stage: "The Key Club Stage (Right Key)",
        start: "11:30",
        end: "12:00",
      },
      {
        name: "Matt Stocks DJ Set",
        stage: "Jägermeister Tent",
        start: "22:00",
        end: "22:55",
      },
    ],
  },
];

export const stagecols = {
  background: {
    "Jägermeister Tent": "bg-yellow-700",
    "The Key Club Stage (Right Key)": "bg-black",
    "The Key Club Stage (Left Key)": "bg-black",
    "punk in drublic": "bg-blue-400",
    "Rock Scene Stage": "bg-red-500",
  },
  text: {
    "Jägermeister Tent": "text-white",
    "The Key Club Stage (Right Key)": "text-white",
    "The Key Club Stage (Left Key)": "text-white",
    "punk in drublic": "text-black",
    "Rock Scene Stage": "text-white",
  },
};

export const bgcols = [
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
  "bg-blue-600",
  "bg-red-600",
  "bg-red-600",
  "bg-blue-600",
];
