export const bands = [
  {
    north: [
      {
        name: "Sum 41",
        stage: "Dickies Stage",
        start: "21:00",
        end: "22:10",
      },
      {
        name: "The Dropkick Murphys",
        stage: "Dickies Stage",
        start: "19:20",
        end: "20:30",
      },
      {
        name: "The Interrupters",
        stage: "Dickies Stage",
        start: "18:10",
        end: "18:55",
      },
      {
        name: "Pennywise",
        stage: "Dickies Stage",
        start: "17:00",
        end: "17:45",
      },
      {
        name: "Streetlight Manifesto",
        stage: "Dickies Stage",
        start: "15:50",
        end: "16:35",
      },
      {
        name: "The Vandals",
        stage: "Dickies Stage",
        start: "14:45",
        end: "15:25",
      },
      {
        name: "Hot Water Music",
        stage: "Dickies Stage",
        start: "13:40",
        end: "14:20",
      },
      {
        name: "The Bronx",
        stage: "Dickies Stage",
        start: "12:35",
        end: "13:15",
      },
      {
        name: "The Suicide Machines",
        stage: "Dickies Stage",
        start: "11:40",
        end: "12:15",
      },
      {
        name: "Alexisonfire",
        stage: "Jägermeister Stage",
        start: "20:20",
        end: "21:30",
      },
      {
        name: "Beartooth",
        stage: "Jägermeister Stage",
        start: "19:05",
        end: "19:55",
      },
      {
        name: "The Used",
        stage: "Jägermeister Stage",
        start: "17:55",
        end: "18:40",
      },
      {
        name: "The Amity Affliction",
        stage: "Jägermeister Stage",
        start: "16:50",
        end: "17:30",
      },
      {
        name: "Electric Callboy",
        stage: "Jägermeister Stage",
        start: "15:45",
        end: "16:25",
      },
      {
        name: "Cancer Bats",
        stage: "Jägermeister Stage",
        start: "14:45",
        end: "15:20",
      },
      {
        name: "Silverstein",
        stage: "Jägermeister Stage",
        start: "13:45",
        end: "14:20",
      },
      {
        name: "Counterparts",
        stage: "Jägermeister Stage",
        start: "12:45",
        end: "13:20",
      },
      {
        name: "Cassyette",
        stage: "Jägermeister Stage",
        start: "11:50",
        end: "12:20",
      },
      {
        name: "Neck Deep",
        stage: "Rock Scene Stage",
        start: "19:50",
        end: "21:00",
      },
      {
        name: "The Story So Far",
        stage: "Rock Scene Stage",
        start: "18:40",
        end: "19:25",
      },
      {
        name: "The Wonder Years",
        stage: "Rock Scene Stage",
        start: "17:30",
        end: "18:15",
      },
      {
        name: "Motion City Soundtrack",
        stage: "Rock Scene Stage",
        start: "16:20",
        end: "17:05",
      },
      {
        name: "Knuckle Puck",
        stage: "Rock Scene Stage",
        start: "15:20",
        end: "15:55",
      },
      {
        name: "Kennyhoopla",
        stage: "Rock Scene Stage",
        start: "14:20",
        end: "14:55",
      },
      {
        name: "Hot Milk",
        stage: "Rock Scene Stage",
        start: "13:20",
        end: "13:55",
      },
      {
        name: "Meet Me At The Altar",
        stage: "Rock Scene Stage",
        start: "12:25",
        end: "12:55",
      },
      {
        name: "Beauty School",
        stage: "Rock Scene Stage",
        start: "11:30",
        end: "12:00",
      },
      {
        name: "Between You and Me",
        stage: "Rock Sound Stage",
        start: "11:30",
        end: "12:00",
      },
      {
        name: "Yours Truly",
        stage: "Rock Sound Stage",
        start: "12:20",
        end: "12:50",
      },
      {
        name: "Chunk! No. Captain Chunk!",
        stage: "Rock Sound Stage",
        start: "13:10",
        end: "13:45",
      },
      {
        name: "Punk Rock Factory",
        stage: "Rock Sound Stage",
        start: "14:05",
        end: "14:40",
      },
      {
        name: "With Confidence",
        stage: "Rock Sound Stage",
        start: "15:00",
        end: "15:35",
      },
      {
        name: "Mod Sun",
        stage: "Rock Sound Stage",
        start: "15:55",
        end: "16:30",
      },
      {
        name: "The Summer Set",
        stage: "Rock Sound Stage",
        start: "16:55",
        end: "17:30",
      },
      {
        name: "Stand Atlantic",
        stage: "Rock Sound Stage",
        start: "17:55",
        end: "18:35",
      },
      {
        name: "Set It Off",
        stage: "Rock Sound Stage",
        start: "19:00",
        end: "19:40",
      },
      {
        name: "30H!3",
        stage: "Rock Sound Stage",
        start: "20:05",
        end: "20:45",
      },
      {
        name: "Deaf Havana",
        stage: "Rock Sound Stage",
        start: "21:10",
        end: "22:00",
      },
      {
        name: "Nova Twins",
        stage: "The Key Club (Left Key Stage)",
        start: "21:00",
        end: "21:40",
      },
      {
        name: "Bears In Trees",
        stage: "The Key Club (Left Key Stage)",
        start: "19:45",
        end: "20:15",
      },
      {
        name: "As December Falls",
        stage: "The Key Club (Left Key Stage)",
        start: "18:35",
        end: "19:05",
      },
      {
        name: "Caskets",
        stage: "The Key Club (Left Key Stage)",
        start: "17:25",
        end: "17:55",
      },
      {
        name: "Hot Mulligan",
        stage: "The Key Club (Left Key Stage)",
        start: "16:15",
        end: "16:45",
      },
      {
        name: "MC Lars",
        stage: "The Key Club (Left Key Stage)",
        start: "15:05",
        end: "15:35",
      },
      {
        name: "Magnolia Park",
        stage: "The Key Club (Left Key Stage)",
        start: "13:55",
        end: "14:25",
      },
      {
        name: "DeathbyRomy",
        stage: "The Key Club (Left Key Stage)",
        start: "12:45",
        end: "13:15",
      },
      {
        name: "Pinkshift",
        stage: "The Key Club (Left Key Stage)",
        start: "11:35",
        end: "12:05",
      },
      {
        name: "Spanish Love Songs",
        stage: "The Key Club (Right Key Stage)",
        start: "20:20",
        end: "20:55",
      },
      {
        name: "The Flatliners",
        stage: "The Key Club (Right Key Stage)",
        start: "19:10",
        end: "19:40",
      },
      {
        name: "Zummo",
        stage: "The Key Club (Right Key Stage)",
        start: "18:00",
        end: "18:30",
      },
      {
        name: "Mom Jeans",
        stage: "The Key Club (Right Key Stage)",
        start: "16:50",
        end: "17:20",
      },
      {
        name: "Point North",
        stage: "The Key Club (Right Key Stage)",
        start: "15:40",
        end: "16:10",
      },
      {
        name: "In Her Own Words",
        stage: "The Key Club (Right Key Stage)",
        start: "14:30",
        end: "15:00",
      },
      {
        name: "Lil Lotus",
        stage: "The Key Club (Right Key Stage)",
        start: "13:20",
        end: "13:50",
      },
      {
        name: "Smrtdeath",
        stage: "The Key Club (Right Key Stage)",
        start: "12:10",
        end: "12:40",
      },
      {
        name: "Zoe London - Closing DJ Set",
        stage: "The Key Club Stage",
        start: "22:00",
        end: "23:00",
      },
    ],
  },
  {
    south: [
      {
        name: "Sum 41",
        stage: "Dickies Stage",
        start: "21:00",
        end: "22:10",
      },
      {
        name: "The Dropkick Murphys",
        stage: "Dickies Stage",
        start: "19:20",
        end: "20:30",
      },
      {
        name: "The Interrupters",
        stage: "Dickies Stage",
        start: "18:10",
        end: "18:55",
      },
      {
        name: "Pennywise",
        stage: "Dickies Stage",
        start: "17:00",
        end: "17:45",
      },
      {
        name: "Streetlight Manifesto",
        stage: "Dickies Stage",
        start: "15:50",
        end: "16:35",
      },
      {
        name: "The Vandals",
        stage: "Dickies Stage",
        start: "14:45",
        end: "15:25",
      },
      {
        name: "Hot Water Music",
        stage: "Dickies Stage",
        start: "13:40",
        end: "14:20",
      },
      {
        name: "The Bronx",
        stage: "Dickies Stage",
        start: "12:35",
        end: "13:15",
      },
      {
        name: "The Suicide Machines",
        stage: "Dickies Stage",
        start: "11:40",
        end: "12:15",
      },
      {
        name: "Alexisonfire",
        stage: "Jägermeister Stage",
        start: "20:20",
        end: "21:30",
      },
      {
        name: "Beartooth",
        stage: "Jägermeister Stage",
        start: "19:05",
        end: "19:55",
      },
      {
        name: "The Used",
        stage: "Jägermeister Stage",
        start: "17:55",
        end: "18:40",
      },
      {
        name: "The Amity Affliction",
        stage: "Jägermeister Stage",
        start: "16:50",
        end: "17:30",
      },
      {
        name: "Electric Callboy",
        stage: "Jägermeister Stage",
        start: "15:45",
        end: "16:25",
      },
      {
        name: "Cancer Bats",
        stage: "Jägermeister Stage",
        start: "14:45",
        end: "15:20",
      },
      {
        name: "Silverstein",
        stage: "Jägermeister Stage",
        start: "13:45",
        end: "14:20",
      },
      {
        name: "Counterparts",
        stage: "Jägermeister Stage",
        start: "12:45",
        end: "13:20",
      },
      {
        name: "Cassyette",
        stage: "Jägermeister Stage",
        start: "11:50",
        end: "12:20",
      },
      {
        name: "Neck Deep",
        stage: "Rock Scene Stage",
        start: "19:50",
        end: "21:00",
      },
      {
        name: "The Story So Far",
        stage: "Rock Scene Stage",
        start: "18:40",
        end: "19:25",
      },
      {
        name: "The Wonder Years",
        stage: "Rock Scene Stage",
        start: "17:30",
        end: "18:15",
      },
      {
        name: "Motion City Soundtrack",
        stage: "Rock Scene Stage",
        start: "16:20",
        end: "17:05",
      },
      {
        name: "Knuckle Puck",
        stage: "Rock Scene Stage",
        start: "15:20",
        end: "15:55",
      },
      {
        name: "Kennyhoopla",
        stage: "Rock Scene Stage",
        start: "14:20",
        end: "14:55",
      },
      {
        name: "Hot Milk",
        stage: "Rock Scene Stage",
        start: "13:20",
        end: "13:55",
      },
      {
        name: "Meet Me At The Altar",
        stage: "Rock Scene Stage",
        start: "12:25",
        end: "12:55",
      },
      {
        name: "Beauty School",
        stage: "Rock Scene Stage",
        start: "11:30",
        end: "12:00",
      },
      {
        name: "Between You and Me",
        stage: "Rock Sound Stage",
        start: "11:30",
        end: "12:00",
      },
      {
        name: "Yours Truly",
        stage: "Rock Sound Stage",
        start: "12:20",
        end: "12:50",
      },
      {
        name: "Chunk! No. Captain Chunk!",
        stage: "Rock Sound Stage",
        start: "13:10",
        end: "13:45",
      },
      {
        name: "Punk Rock Factory",
        stage: "Rock Sound Stage",
        start: "14:05",
        end: "14:40",
      },
      {
        name: "With Confidence",
        stage: "Rock Sound Stage",
        start: "15:00",
        end: "15:35",
      },
      {
        name: "Mod Sun",
        stage: "Rock Sound Stage",
        start: "15:55",
        end: "16:30",
      },
      {
        name: "The Summer Set",
        stage: "Rock Sound Stage",
        start: "16:55",
        end: "17:30",
      },
      {
        name: "Stand Atlantic",
        stage: "Rock Sound Stage",
        start: "17:55",
        end: "18:35",
      },
      {
        name: "Set It Off",
        stage: "Rock Sound Stage",
        start: "19:00",
        end: "19:40",
      },
      {
        name: "30H!3",
        stage: "Rock Sound Stage",
        start: "20:05",
        end: "20:45",
      },
      {
        name: "Deaf Havana",
        stage: "Rock Sound Stage",
        start: "21:10",
        end: "22:00",
      },
      {
        name: "Nova Twins",
        stage: "The Key Club (Left Key Stage)",
        start: "21:00",
        end: "21:40",
      },
      {
        name: "Bears In Trees",
        stage: "The Key Club (Left Key Stage)",
        start: "19:45",
        end: "20:15",
      },
      {
        name: "As December Falls",
        stage: "The Key Club (Left Key Stage)",
        start: "18:35",
        end: "19:05",
      },
      {
        name: "Caskets",
        stage: "The Key Club (Left Key Stage)",
        start: "11:35",
        end: "12:05",
      },
      {
        name: "Hot Mulligan",
        stage: "The Key Club (Left Key Stage)",
        start: "16:15",
        end: "16:45",
      },
      {
        name: "MC Lars",
        stage: "The Key Club (Left Key Stage)",
        start: "15:05",
        end: "15:35",
      },
      {
        name: "Magnolia Park",
        stage: "The Key Club (Left Key Stage)",
        start: "17:25",
        end: "17:55",
      },
      {
        name: "DeathbyRomy",
        stage: "The Key Club (Left Key Stage)",
        start: "12:45",
        end: "13:15",
      },
      {
        name: "Pinkshift",
        stage: "The Key Club (Left Key Stage)",
        start: "13:55",
        end: "14:25",
      },
      {
        name: "Spanish Love Songs",
        stage: "The Key Club (Right Key Stage)",
        start: "20:20",
        end: "20:55",
      },
      {
        name: "The Flatliners",
        stage: "The Key Club (Right Key Stage)",
        start: "19:10",
        end: "19:40",
      },
      {
        name: "Zummo",
        stage: "The Key Club (Right Key Stage)",
        start: "12:10",
        end: "12:40",
      },
      {
        name: "Mom Jeans",
        stage: "The Key Club (Right Key Stage)",
        start: "16:50",
        end: "17:20",
      },
      {
        name: "Point North",
        stage: "The Key Club (Right Key Stage)",
        start: "13:20",
        end: "13:50",
      },
      {
        name: "In Her Own Words",
        stage: "The Key Club (Right Key Stage)",
        start: "14:30",
        end: "15:00",
      },
      {
        name: "Lil Lotus",
        stage: "The Key Club (Right Key Stage)",
        start: "18:00",
        end: "18:30",
      },
      {
        name: "Smrtdeath",
        stage: "The Key Club (Right Key Stage)",
        start: "15:40",
        end: "16:10",
      },
      {
        name: "Zoe London - Closing DJ Set",
        stage: "The Key Club Stage",
        start: "22:00",
        end: "23:00",
      },
    ],
  },
];

export const stagecols = {
  background: {
    "Jägermeister Stage": "bg-yellow-700",
    "The Key Club (Right Key Stage)": "bg-black",
    "The Key Club (Left Key Stage)": "bg-black",
    "Rock Sound Stage": "bg-green-800",
    "Rock Scene Stage": "bg-red-800",
    "Dickies Stage": "bg-blue-800",
  },
  text: {
    "Jägermeister Stage": "text-white",
    "The Key Club (Right Key Stage)": "text-white",
    "The Key Club (Left Key Stage)": "text-white",
    "Rock Sound Stage": "text-white",
    "Rock Scene Stage": "text-white",
    "Dickies Stage": "text-white",
  },
};

export const bgcols = [
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
  "bg-blue-800",
  "bg-red-800",
  "bg-red-800",
  "bg-blue-800",
];
